#include "uart.h"
#include <stdarg.h>
#include <stdio.h>
#include "stm32h7xx_hal.h"

/*
 * UART handle is normally generated
 * by STM32CubeMX.
 */
extern UART_HandleTypeDef huart3;

bool UART_Init(void)
{
    /*
     * UART peripheral initialization is
     * normally generated by CubeMX.
     */

    return true;
}

void UART_SendChar(char character)
{
    HAL_UART_Transmit(
        &huart3,
        (uint8_t *)&character,
        1,
        HAL_MAX_DELAY
    );
}

void UART_SendString(const char *text)
{
    if (text == 0)
    {
        return;
    }

    while (*text != '\0')
    {
        UART_SendChar(*text);
        text++;
    }
}

void UART_Printf(const char *format, ...)
{
    char buffer[128];

    va_list args;

    va_start(args, format);

    vsnprintf(buffer,
              sizeof(buffer),
              format,
              args);

    va_end(args);

    UART_SendString(buffer);
}

bool UART_ReceiveChar(char *character)
{
    if (character == 0)
    {
        return false;
    }

    return (
        HAL_UART_Receive(
            &huart3,
            (uint8_t *)character,
            1,
            0
        ) == HAL_OK
    );
}

bool UART_DataAvailable(void)
{
    /*
     * Implement using interrupt/DMA
     * receive mechanism in production.
     */

    return false;
}
